version: "3.8"

networks:
  web:
    external: true

volumes:
  email_builder_data:
    external: true

services:
  email-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-builder
    restart: always
    networks:
      - default
      - web
    ports:
      - "5173:5173"
    volumes:
      - email_builder_data:/app/packages/editor-sample/data
